/* Educational reference only. Not diagnostic. Not used in CBI scoring. */
const DISORDERS = [
  // Anxiety
  { category: 'anxiety', name: 'Generalized Anxiety Disorder (GAD)',
    description: 'Persistent, excessive worry across domains, often with restlessness, muscle tension, sleep disturbance, and difficulty concentrating.',
    stressNote: 'Chronic uncertainty and high recovery deficit commonly maintain symptoms.' },
  { category: 'anxiety', name: 'Panic Disorder',
    description: 'Recurrent unexpected panic attacks and ongoing concern about further attacks or their consequences, often with avoidance.',
    stressNote: 'Acute autonomic surges can be triggered or amplified under overload.' },
  { category: 'anxiety', name: 'Social Anxiety Disorder',
    description: 'Marked fear of social or performance situations involving possible scrutiny, leading to avoidance or intense distress.',
    stressNote: 'Evaluative workplaces and display rules can intensify symptoms.' },
  { category: 'anxiety', name: 'Specific Phobia',
    description: 'Marked fear of a specific object or situation, out of proportion to actual danger, with active avoidance.',
    stressNote: 'Usually less tied to global allostatic load than GAD, but acute stress can lower thresholds.' },
  { category: 'anxiety', name: 'Agoraphobia',
    description: 'Fear of situations where escape or help might be difficult if panic-like or other incapacitating symptoms occur.',
    stressNote: 'Can expand after panic experiences under prolonged strain.' },
  { category: 'anxiety', name: 'Separation Anxiety Disorder',
    description: 'Developmentally inappropriate fear of separation from attachment figures; occurs in children and can persist or begin in adults.',
    stressNote: 'Loss, instability, or high threat contexts can worsen severity.' },

  // Mood
  { category: 'mood', name: 'Major Depressive Disorder',
    description: 'Episodes of depressed mood or anhedonia with additional symptoms such as sleep/appetite change, fatigue, worthlessness, concentration problems, or suicidal thoughts.',
    stressNote: 'Learned helplessness, chronic toxic load, and sleep disruption are major correlational pathways.' },
  { category: 'mood', name: 'Persistent Depressive Disorder (Dysthymia)',
    description: 'Long-lasting, lower-grade depressive symptoms lasting years, often with intermittent major episodes.',
    stressNote: 'Sustained erosive stress without recovery windows can maintain chronic low mood.' },
  { category: 'mood', name: 'Bipolar I Disorder',
    description: 'At least one manic episode; depressive episodes are common but not required for the diagnosis.',
    stressNote: 'Sleep loss and extreme demand can precipitate mood episodes in vulnerable people.' },
  { category: 'mood', name: 'Bipolar II Disorder',
    description: 'Pattern of hypomanic episodes and major depressive episodes, without full mania.',
    stressNote: 'Circadian disruption and prolonged overload are recognized episode triggers for many.' },
  { category: 'mood', name: 'Cyclothymic Disorder',
    description: 'Chronic fluctuating hypomanic and depressive symptoms that do not meet full episode criteria for long periods.',
    stressNote: 'Irregular schedules and recovery deficit can amplify mood instability.' },
  { category: 'mood', name: 'Premenstrual Dysphoric Disorder (PMDD)',

    description: 'Severe mood and physical symptoms in the premenstrual phase that markedly impair function, resolving after menses begin.',
    stressNote: 'Baseline toxic load can worsen cycle-linked vulnerability.' },

  // Trauma
  { category: 'trauma', name: 'Posttraumatic Stress Disorder (PTSD)',
    description: 'Intrusion symptoms, avoidance, negative alterations in cognition/mood, and arousal changes following exposure to actual or threatened death, serious injury, or sexual violence.',
    stressNote: 'Prior allostatic load and ongoing uncontrollability can deepen course; recovery and safety are central.' },
  { category: 'trauma', name: 'Acute Stress Disorder',
    description: 'PTSD-like symptoms in the first month after trauma.',
    stressNote: 'Early support and reduced secondary stress matter for trajectory.' },
  { category: 'trauma', name: 'Adjustment Disorders',
    description: 'Emotional or behavioral symptoms in response to an identifiable stressor, out of proportion or impairing, not meeting criteria for another specific disorder.',
    stressNote: 'Directly defined by stressor exposure; classic early-signal category in occupational strain.' },
  { category: 'trauma', name: 'Complex trauma presentations (clinical descriptor)',
    description: 'Not a single universal DSM code; refers to difficulties in regulation, self-concept, and relationships after prolonged/repeated trauma (e.g. childhood abuse).',
    stressNote: 'Chronic uncontrollability is central to the developmental pathway.' },

  // OCD-related
  { category: 'ocd', name: 'Obsessive–Compulsive Disorder (OCD)',
    description: 'Obsessions (intrusive thoughts/urges) and/or compulsions (repetitive behaviors or mental acts) that are time-consuming or impairing.',
    stressNote: 'Stress commonly exacerbates rituals; load reduces inhibition capacity.' },
  { category: 'ocd', name: 'Body Dysmorphic Disorder',
    description: 'Preoccupation with perceived appearance defects with repetitive checking, comparing, or grooming behaviors.',
    stressNote: 'Social evaluation pressure can intensify symptoms.' },
  { category: 'ocd', name: 'Hoarding Disorder',
    description: 'Persistent difficulty discarding possessions regardless of value, with accumulation that compromises living space.',
    stressNote: 'Executive load and anxiety about decision-making interact with the behavior.' },
  { category: 'ocd', name: 'Trichotillomania / Excoriation',
    description: 'Recurrent hair-pulling or skin-picking resulting in loss or lesions, with repeated attempts to stop.',
    stressNote: 'Often increases under tension or boredom-as-strain.' },

  // Psychotic
  { category: 'psychotic', name: 'Schizophrenia',
    description: 'Persistent disturbance involving delusions, hallucinations, disorganized speech/behavior, and/or negative symptoms, with functional decline.',
    stressNote: 'Stress–vulnerability models treat substantial stress as a possible precipitant, not a primary cause for most people.' },
  { category: 'psychotic', name: 'Schizoaffective Disorder',
    description: 'Major mood episode concurrent with schizophrenia-spectrum psychotic symptoms, with periods of psychosis without prominent mood symptoms.',
    stressNote: 'Mood and psychotic pathways both can be sensitive to sleep and load.' },
  { category: 'psychotic', name: 'Brief Psychotic Disorder',
    description: 'Sudden psychotic symptoms lasting more than a day and less than a month, with eventual return to baseline.',
    stressNote: 'Often linked to acute marked stressors in vulnerable individuals.' },
  { category: 'psychotic', name: 'Delusional Disorder',
    description: 'One or more delusions lasting a month or longer without the broader symptom picture of schizophrenia.',
    stressNote: 'Isolation and threat-focused environments can reinforce belief systems.' },
  { category: 'psychotic', name: 'Substance/Medication-Induced Psychotic Disorder',
    description: 'Delusions or hallucinations judged to be due to substance intoxication, withdrawal, or medication effects.',
    stressNote: 'Links substance load factors to acute risk in the broader systems model.' },

  // Personality
  { category: 'personality', name: 'Borderline Personality Disorder',
    description: 'Pervasive instability of relationships, self-image, and affects, with impulsivity and intense fear of abandonment.',
    stressNote: 'Emotional load and invalidating or chaotic contexts strongly affect course.' },
  { category: 'personality', name: 'Antisocial Personality Disorder',
    description: 'Pervasive pattern of disregard for and violation of the rights of others, beginning in childhood/adolescence and continuing into adulthood.',
    stressNote: 'Distinct from ordinary workplace strain; included for educational completeness.' },
  { category: 'personality', name: 'Avoidant Personality Disorder',
    description: 'Pervasive social inhibition, feelings of inadequacy, and hypersensitivity to negative evaluation.',
    stressNote: 'Overlaps dimensionally with social anxiety under chronic evaluation pressure.' },
  { category: 'personality', name: 'Obsessive–Compulsive Personality Disorder',
    description: 'Preoccupation with orderliness, perfectionism, and control at the expense of flexibility and efficiency (distinct from OCD).',
    stressNote: 'Can drive compensatory overwork and recovery failure under demand.' },
  { category: 'personality', name: 'Narcissistic Personality Disorder',
    description: 'Pervasive grandiosity, need for admiration, and lack of empathy, with vulnerability to criticism underneath in many models.',
    stressNote: 'Status threat and evaluation systems can trigger intense reactivity.' },

  // Neurodevelopmental
  { category: 'neurodev', name: 'Attention-Deficit/Hyperactivity Disorder (ADHD)',
    description: 'Persistent pattern of inattention and/or hyperactivity–impulsivity that interferes with function or development.',
    stressNote: 'High interruption and working-memory demand environments are especially costly; supports change capacity use.' },
  { category: 'neurodev', name: 'Autism Spectrum Disorder',
    description: 'Persistent differences in social communication and restricted/repetitive patterns of behavior, interests, or sensory processing.',
    stressNote: 'Sensory and social environmental load can drive toxic stress without implying the neurology is an illness of character.' },
  { category: 'neurodev', name: 'Specific Learning Disorder',
    description: 'Persistent difficulties in reading, written expression, or mathematics below expected level given age and opportunity.',
    stressNote: 'Mismatch between task design and profile elevates extraneous load.' },
  { category: 'neurodev', name: 'Intellectual Developmental Disorder',
    description: 'Deficits in intellectual and adaptive functioning with onset during the developmental period.',
    stressNote: 'Support design and recovery access determine much of lived strain.' },

  // Substance
  { category: 'substance', name: 'Alcohol Use Disorder',
    description: 'Problematic pattern of alcohol use leading to impairment or distress, with control, craving, tolerance, or withdrawal features.',
    stressNote: 'Often intertwined with attempts to regulate toxic stress; worsens sleep and recovery.' },
  { category: 'substance', name: 'Opioid Use Disorder',
    description: 'Problematic opioid use with loss of control, continued use despite harm, and often tolerance/withdrawal.',
    stressNote: 'Pain, trauma, and erosive stress histories are common correlational contexts.' },
  { category: 'substance', name: 'Stimulant Use Disorder',
    description: 'Problematic use of stimulants (e.g. cocaine, amphetamines) with compulsive use and impairment.',
    stressNote: 'May begin as performance compensation under extreme demand.' },
  { category: 'substance', name: 'Cannabis Use Disorder',
    description: 'Problematic cannabis use with control impairment and continued use despite consequences.',
    stressNote: 'Sometimes used for anxiety/sleep under load; effects on motivation and recovery vary.' },

  // Other / historical
  { category: 'other', name: 'Insomnia Disorder',
    description: 'Dissatisfaction with sleep quantity or quality with difficulty initiating or maintaining sleep, causing daytime impairment.',
    stressNote: 'Bidirectional with toxic load; key hinge in the dynamic CBI model.' },
  { category: 'other', name: 'Somatic Symptom Disorder',
    description: 'One or more somatic symptoms that are distressing with excessive thoughts, feelings, or behaviors related to them.',
    stressNote: 'Autonomic arousal from chronic stress can feed symptom focus.' },
  { category: 'other', name: 'Illness Anxiety Disorder',
    description: 'Preoccupation with having or acquiring a serious illness, with high anxiety and health checking or avoidance.',
    stressNote: 'Uncertainty intolerance under load amplifies health threat monitoring.' },
  { category: 'other', name: 'Burnout (occupational phenomenon, ICD-11)',
    description: 'Syndrome from chronic workplace stress that has not been successfully managed: exhaustion, mental distance/cynicism, and reduced professional efficacy.',
    stressNote: 'Maps closely to prolonged high CBI with low recovery — not identical to clinical depression.' },
  { category: 'other', name: 'Neurosis (historical term)',
    description: 'Older label for anxiety, depressive, and related presentations without psychosis. Largely replaced by specific categories in modern manuals.',
    stressNote: 'Retained only as conceptual history for educational reading of older literature.' },
  { category: 'other', name: 'Nervous breakdown (colloquial)',
    description: 'Non-clinical phrase for acute inability to function under overwhelming stress; not a formal diagnosis.',
    stressNote: 'Often describes a peak of toxic load with collapsed recovery.' },
  { category: 'other', name: 'Eating disorders (AN, BN, BED — overview)',
    description: 'Anorexia nervosa, bulimia nervosa, and binge-eating disorder involve persistent disturbance of eating and related thoughts/behaviors with health or function impact.',
    stressNote: 'Control, emotion regulation, and body-related threat often intensify under stress.' },
  { category: 'other', name: 'Dissociative disorders (overview)',
    description: 'Disruptions of consciousness, memory, identity, or perception (e.g. dissociative amnesia, depersonalization, dissociative identity disorder).',
    stressNote: 'Strong historical links to overwhelming trauma and inescapable stress.' }
];
