/* Educational positive paradigms — not scored in CBI calculator. */
const PARADIGMS = [
  // Attitudes
  { category: 'attitude', name: 'Growth mindset',
    description: 'Treating abilities and coping skills as developable through effort, strategy, and feedback rather than fixed traits.',
    outcome: 'Supports learning under adaptive stress; reduces helplessness after setbacks.' },
  { category: 'attitude', name: 'Self-compassion',
    description: 'Responding to personal struggle with kindness, common humanity, and mindful awareness instead of harsh self-attack.',
    outcome: 'Lowers secondary emotional load; associated with better recovery after failure.' },
  { category: 'attitude', name: 'Realistic optimism',
    description: 'Expecting that effort and problem-solving can improve outcomes without denying constraints or risk.',
    outcome: 'Sustains agency without magical thinking.' },
  { category: 'attitude', name: 'Acceptance of controllable vs uncontrollable',
    description: 'Clear discrimination between what can be influenced and what must be adapted to.',
    outcome: 'Protects against learned helplessness and wasted regulatory effort.' },
  { category: 'attitude', name: 'Intellectual humility',
    description: 'Willingness to revise beliefs, admit uncertainty, and learn from others.',
    outcome: 'Reduces interpersonal conflict load and identity-threat reactivity.' },
  { category: 'attitude', name: 'Purpose orientation',
    description: 'Connecting daily effort to valued aims larger than immediate discomfort.',
    outcome: 'Can convert demand into adaptive stress when recovery is present.' },

  // Behaviors
  { category: 'behavior', name: 'Protective sleep prioritization',
    description: 'Treating sleep opportunity as non-negotiable infrastructure for cognition and mood.',
    outcome: 'Strongest practical counterweight to latent allostatic accumulation.' },
  { category: 'behavior', name: 'Boundary setting',
    description: 'Clear limits on after-hours work, availability, and role creep.',
    outcome: 'Preserves recovery opportunity and controllability.' },
  { category: 'behavior', name: 'Help-seeking',
    description: 'Asking for information, prioritization, or support early rather than after collapse.',
    outcome: 'Interrupts isolation and backlog spirals.' },
  { category: 'behavior', name: 'Task batching / deep-work blocks',
    description: 'Grouping similar work and protecting uninterrupted time.',
    outcome: 'Cuts extraneous switching and interruption density.' },
  { category: 'behavior', name: 'Micro-recovery rituals',
    description: 'Brief, repeatable resets: breath, movement, gaze rest, water, short walks between intense blocks.',
    outcome: 'Lowers continuous arousal without requiring full days off.' },
  { category: 'behavior', name: 'Values-based time allocation',
    description: 'Scheduling energy toward high-value work and relationships first, not only urgency.',
    outcome: 'Reduces regret load and chronic role conflict.' },
  { category: 'behavior', name: 'Substance moderation / abstinence when indicated',
    description: 'Limiting alcohol and other substances that impair sleep and regulation.',
    outcome: 'Protects recovery quality and next-day capacity.' },
  { category: 'behavior', name: 'Physical activity as regulation',
    description: 'Regular movement used deliberately for mood, sleep, and stress physiology — scaled to ability.',
    outcome: 'Supports adaptive stress and metabolic health.' },

  // Emotional skills
  { category: 'emotion', name: 'Emotion labeling',
    description: 'Naming felt states with precision (e.g. “irritated and behind” vs vague “bad”).',
    outcome: 'Improves regulation and reduces diffuse anxiety.' },
  { category: 'emotion', name: 'Distress tolerance',
    description: 'Capacity to stay present with discomfort without impulsive escape that worsens outcomes.',
    outcome: 'Prevents short-term relief strategies that raise long-term toxic load.' },
  { category: 'emotion', name: 'Cognitive reappraisal',
    description: 'Reinterpreting situations to change emotional impact without denying facts.',
    outcome: 'Classic adaptive strategy under demand.' },
  { category: 'emotion', name: 'Gratitude practice (evidence-based dose)',
    description: 'Brief, genuine attention to specific positives — not forced positivity.',
    outcome: 'Small average benefits for mood and social connection when authentic.' },
  { category: 'emotion', name: 'Anger as information',
    description: 'Using anger to detect boundary violations and values, then choosing proportional response.',
    outcome: 'Channels energy without chronic hostility load.' },

  // Mental models
  { category: 'model', name: 'Stress is neutral; toxicity is imbalance',
    description: 'Demand can grow capacity when recovery and agency keep pace; harm comes from prolonged mismatch.',
    outcome: 'Core model of this lab; guides prevention rather than total stress avoidance.' },
  { category: 'model', name: 'Systems thinking',
    description: 'Seeing outcomes as products of interacting factors (sleep, load, support, body, context) rather than single blame points.',
    outcome: 'Improves intervention targeting.' },
  { category: 'model', name: 'Implementation intentions',
    description: 'If-then plans that link cues to actions (e.g. “If it is 10pm, devices leave the bedroom”).',
    outcome: 'Raises follow-through under cognitive load.' },
  { category: 'model', name: 'OODA / tight feedback loops',
    description: 'Observe–orient–decide–act cycles with rapid correction instead of rigid plans only.',
    outcome: 'Supports adaptation under changing demand.' },
  { category: 'model', name: 'Minimum effective dose',
    description: 'Seeking the smallest intervention that reliably improves recovery or load — not maximal effort theater.',
    outcome: 'Prevents compensatory overwork.' },
  { category: 'model', name: 'Margin / slack as design requirement',
    description: 'Treating unused capacity as safety infrastructure, not waste.',
    outcome: 'Keeps stress adaptive when surprises arrive.' },

  // Philosophies
  { category: 'philosophy', name: 'Stoic dichotomy of control (practical)',
    description: 'Focus effort on judgments and actions; accept externals that cannot be moved today.',
    outcome: 'Aligns with controllability factor; reduces helplessness.' },
  { category: 'philosophy', name: 'Pragmatism',
    description: 'Evaluating ideas by workable consequences rather than purity of ideology.',
    outcome: 'Supports flexible coping and reduced identity threat.' },
  { category: 'philosophy', name: 'Human dignity as baseline',
    description: 'Treating self and others as worthy of respect independent of productivity rank.',
    outcome: 'Counters depersonalization and harsh self-models under burnout risk.' },
  { category: 'philosophy', name: 'Long-game ethics',
    description: 'Preferring sustainable contribution over short-term extraction from self or others.',
    outcome: 'Aligns personal success with lower toxic load trajectories.' },
  { category: 'philosophy', name: 'Curiosity over certainty',
    description: 'Defaulting to questions when threatened, before rigid defense.',
    outcome: 'Lowers conflict escalation and cognitive tunneling.' },

  // Social / relational
  { category: 'social', name: 'Secure-leaning attachment behaviors',
    description: 'Signaling reliability, seeking support, and offering it without enmeshment or total withdrawal.',
    outcome: 'Builds support factor that buffers toxic stress.' },
  { category: 'social', name: 'Fair conflict habits',
    description: 'Specific complaints, no character attacks, repair attempts after rupture.',
    outcome: 'Reduces chronic interpersonal emotional load.' },
  { category: 'social', name: 'Mentorship and peer consultation',
    description: 'Regular access to people who can reality-test priorities and normalize struggle.',
    outcome: 'Increases controllability and reduces isolation.' },
  { category: 'social', name: 'Contribution / prosocial action',
    description: 'Small, sustainable acts that help others without self-erasure.',
    outcome: 'Associated with meaning and reciprocal support.' },
  { category: 'social', name: 'Respect for difference without contempt',
    description: 'Disagreeing on ideas while refusing dehumanization.',
    outcome: 'Lowers collective threat climate that raises everyone’s baseline load.' },

  // Recovery practices
  { category: 'recovery', name: 'Psychological detachment after work',
    description: 'Mentally leaving the role: shutdown rituals, hobby absorption, nature, play.',
    outcome: 'Directly raises recovery opportunity quality.' },
  { category: 'recovery', name: 'Nature contact',
    description: 'Time in green or blue space scaled to access and ability.',
    outcome: 'Modest average benefits for rumination and physiological arousal.' },
  { category: 'recovery', name: 'Breath and down-regulation skills',
    description: 'Slow breathing, progressive relaxation, or similar tools used as skills, not magic.',
    outcome: 'Helps acute arousal without replacing structural recovery.' },
  { category: 'recovery', name: 'Social rest',
    description: 'Choosing restorative versus draining social contexts deliberately.',
    outcome: 'Matches extraversion/introversion needs to recovery design.' },
  { category: 'recovery', name: 'Creative absorption / flow hobbies',
    description: 'Activities that fully engage attention without performance ranking.',
    outcome: 'Interrupts perseverative cognition and rebuilds agency.' },
  { category: 'recovery', name: 'Scheduled nothing',
    description: 'Unstructured time protected from optimization.',
    outcome: 'Counterweight to continuous demand culture.' }
];
