/* Educational CBT skills — not therapy delivery, not CBI scored. */
const CBT_SKILLS = [
  { category: 'cognitive', name: 'Cognitive model (situation → thought → emotion → behavior)',
    description: 'Events do not uniquely determine feelings; interpretations and meanings shape emotional and behavioral responses.',
    how: 'Map a recent stress spike: situation, automatic thought, emotion intensity, what you did next.',
    cbiLink: 'Separates external demand from appraisal — useful when emotional load is high.',
    limits: 'Does not remove real structural load (understaffing, unsafe environment).' },
  { category: 'cognitive', name: 'Identifying cognitive distortions',
    description: 'Recognizing patterns such as catastrophizing, mind-reading, all-or-nothing thinking, fortune-telling, and discounting positives.',
    how: 'Label the pattern without self-attack; ask what evidence supports and contradicts the thought.',
    cbiLink: 'Reduces secondary emotional load layered on top of primary demand.',
    limits: 'Labeling is not the same as forced positive thinking.' },
  { category: 'cognitive', name: 'Thought record',
    description: 'Structured written examination of automatic thoughts, evidence, and alternative balanced thoughts.',
    how: 'Columns: situation, emotion, automatic thought, evidence for/against, alternative, re-rate emotion.',
    cbiLink: 'Targets rumination and helplessness expectancy.',
    limits: 'Harder when exhausted; start brief.' },
  { category: 'cognitive', name: 'Cognitive reappraisal',
    description: 'Deliberately changing the meaning of a situation to alter its emotional impact while staying factual.',
    how: 'Ask: What else could this mean? What would I tell a friend? What part is controllable today?',
    cbiLink: 'Supports adaptive stress when recovery and agency exist.',
    limits: 'Invalid if used to deny abuse or unsafe conditions.' },
  { category: 'cognitive', name: 'Decatastrophizing',
    description: 'Testing worst-case predictions and planning coping for realistic bad outcomes.',
    how: 'Worst case, best case, most likely case; coping plan for the realistic case.',
    cbiLink: 'Lowers time-pressure amplification from threat overestimation.',
    limits: 'Not for acute safety emergencies — act on real danger.' },
  { category: 'cognitive', name: 'Behavioral experiment',
    description: 'Testing a belief with a small real-world trial instead of arguing only in the head.',
    how: 'Prediction → small test → observe result → update belief.',
    cbiLink: 'Rebuilds controllability and reduces avoidance.',
    limits: 'Design tests that are safe and ethical.' },

  { category: 'behavioral', name: 'Behavioral activation',
    description: 'Scheduling valued or mastery activities even when motivation is low, to interrupt withdrawal spirals.',
    how: 'List small activities by value/mastery; schedule 1–2 daily; rate mood before/after.',
    cbiLink: 'Counters depressive correlates of toxic load and anhedonia.',
    limits: 'Not a substitute for treatment of severe depression.' },
  { category: 'behavioral', name: 'Exposure principles (educational)',
    description: 'Gradual, planned contact with feared but safe situations to reduce avoidance learning.',
    how: 'Fear hierarchy from easier to harder; stay until anxiety peaks and falls; no subtle safety behaviors if possible.',
    cbiLink: 'Relevant when avoidance maintains anxiety under evaluation pressure.',
    limits: 'Trauma exposure belongs with trained clinicians.' },
  { category: 'behavioral', name: 'Activity scheduling & pacing',
    description: 'Balancing demand blocks with recovery so effort stays sustainable.',
    how: 'Alternate high-demand and recovery; protect sleep; use time-boxes.',
    cbiLink: 'Directly raises recovery opportunity and cuts compensatory overwork.',
    limits: 'Needs organizational permission in some jobs.' },
  { category: 'behavioral', name: 'Problem-solving training',
    description: 'Structured steps: define problem, generate options, weigh, choose, review.',
    how: 'Write the problem in one sentence; brainstorm without judging; pick one next action.',
    cbiLink: 'Increases agency when low controllability is partly solvable.',
    limits: 'Some problems are structural — strategy may be boundary or exit, not heroic coping.' },
  { category: 'behavioral', name: 'Opposite action (when emotion drives unhelpful behavior)',
    description: 'When an emotion urges a behavior that worsens outcomes, act opposite to the urge (skill from CBT/DBT overlap).',
    how: 'Identify urge → check if emotion fits facts → if not, act opposite in small dose.',
    cbiLink: 'Interrupts avoidance and hostility spirals under emotional load.',
    limits: 'Not for ignoring valid anger about injustice — channel, don’t suppress forever.' },

  { category: 'physiological', name: 'Diaphragmatic / slow breathing',
    description: 'Slow, longer-exhale breathing to down-regulate acute arousal.',
    how: 'Inhale comfortably, longer exhale, 1–3 minutes; practice outside peak panic first.',
    cbiLink: 'Acute tool when emotional load and arousal spike.',
    limits: 'Does not fix chronic understaffing or trauma by itself.' },
  { category: 'physiological', name: 'Sleep hygiene as behavior change',
    description: 'Consistent schedule, light/dark cues, reduced evening stimulants, wind-down routine.',
    how: 'Pick 1–2 changes; protect a fixed wake time; reduce bed-with-screens.',
    cbiLink: 'Sleep disruption is a major CBI factor and dynamic hinge.',
    limits: 'Insomnia disorder may need CBT-I with a clinician.' },
  { category: 'physiological', name: 'Progressive muscle relaxation',
    description: 'Systematic tense–release of muscle groups to reduce somatic tension.',
    how: '10–15 minutes, feet to face, notice contrast between tension and release.',
    cbiLink: 'Addresses somatic correlates of sustained threat monitoring.',
    limits: 'Adapt for pain or injury.' },

  { category: 'relapse', name: 'Early-warning sign monitoring',
    description: 'Personal list of thoughts, body signals, sleep changes, and behaviors that precede erosive overload.',
    how: 'Write 5 early signs; pair each with a pre-planned response (sleep, boundary, help-seek).',
    cbiLink: 'Maps to timeline drift into erosive risk before toxic load.',
    limits: 'Requires honest tracking without self-punishment.' },
  { category: 'relapse', name: 'If–then coping plans',
    description: 'Implementation intentions that link triggers to specific responses.',
    how: 'If I am still working at 9pm, then I send a shutdown message and stop.',
    cbiLink: 'Protects recovery opportunity under habit pressure.',
    limits: 'Plans need environmental support to stick.' },
  { category: 'relapse', name: 'Values-based recommitment after setbacks',
    description: 'Returning to valued action after a bad day without all-or-nothing collapse.',
    how: 'Name the value; one small action tomorrow; no moral global rating of the self.',
    cbiLink: 'Prevents compensatory overwork and helplessness after failure.',
    limits: 'Not an excuse to ignore repeated burnout signals from the system.' },

  { category: 'interpersonal', name: 'Assertive communication',
    description: 'Clear, respectful requests and refusals without aggression or total submission.',
    how: 'Situation–feeling–request; practice short scripts for common load sources.',
    cbiLink: 'Raises controllability and can reduce emotional labor.',
    limits: 'Unsafe power dynamics may make assertiveness risky — prioritize safety.' },
  { category: 'interpersonal', name: 'Support mobilization',
    description: 'Identifying who can help with which kind of load (practical, emotional, informational).',
    how: 'Map 3 people/resources; make one specific ask this week.',
    cbiLink: 'Directly targets low social support factor.',
    limits: 'Support is not always available; structural advocacy may also be needed.' }
];
