const GLOSSARY = [
  { id: 'adaptive-stress', term: 'Adaptive stress', lab: true,
    def: 'Demand that remains within capacity because recovery, agency, and support keep pace. Can support growth and learning. Opposite of erosive/toxic load in this lab’s language.' },
  { id: 'allostasis', term: 'Allostasis',
    def: 'Stability through change: anticipatory physiological adjustments that meet expected demand (Sterling & Eyer). Contrasts with a purely fixed set-point view of homeostasis.' },
  { id: 'allostatic-load', term: 'Allostatic load',
    def: 'Cumulative cost of chronic or repeated adaptation when stress systems are overused, fail to shut off, or respond poorly (McEwen and colleagues).' },
  { id: 'allostatic-overload', term: 'Allostatic overload',
    def: 'Stage at which cumulative wear becomes frankly pathogenic; used in McEwen’s framework beyond ordinary allostatic load.' },
  { id: 'cbi', term: 'Cognitive Burden Index (CBI)', lab: true,
    def: 'Exploratory 0–100 composite in this lab combining weighted process factors, optional demand×controllability amplification, and optional dynamic latent load. Not a published clinical scale.' },
  { id: 'cognitive-ergonomics', term: 'Cognitive ergonomics',
    def: 'Domain of ergonomics/human factors focused on mental processes (attention, memory, decision, perception) in interaction with tasks, tools, and environments.' },
  { id: 'cognitive-load-theory', term: 'Cognitive load theory (CLT)',
    def: 'Framework (Sweller et al.) distinguishing intrinsic, extraneous, and germane load in learning and task design; emphasizes reducing unnecessary demand on working memory.' },
  { id: 'controllability', term: 'Controllability / agency',
    def: 'Extent to which a person can influence pace, priorities, or method. Low controllability is treated here as amplifying demand cost (related to demand–control ideas).' },
  { id: 'demand-control', term: 'Demand–control model',
    def: 'Occupational model (Karasek) in which high psychological demand combined with low decision latitude predicts strain.' },
  { id: 'erosive-risk', term: 'Erosive risk', lab: true,
    def: 'CBI zone indicating prolonged imbalance without adequate recovery; early intervention window before frankly toxic load.' },
  { id: 'extraneous-load', term: 'Extraneous load',
    def: 'In CLT, load imposed by poor design (e.g. unnecessary interruption or switching) rather than by the essential difficulty of the material.' },
  { id: 'germane-load', term: 'Germane load',
    def: 'In CLT, productive processing that builds schemas and learning; desired when capacity is available.' },
  { id: 'homeostasis', term: 'Homeostasis',
    def: 'Maintenance of internal variables near set-points through regulatory feedback; classical complement/contrast to allostasis.' },
  { id: 'intrinsic-load', term: 'Intrinsic load',
    def: 'In CLT, load inherent in the complexity of the content or task relative to the learner’s prior knowledge.' },
  { id: 'latent-l', term: 'Latent load (L)', lab: true,
    def: 'Toy state variable in this lab that rises with sustained load and falls with recovery opportunity; maps to dynamic CBI via L/(L+K).' },
  { id: 'locus', term: 'Locus (of a factor)', lab: true,
    def: 'Tag indicating whether a process factor is primarily work-design, individual, relational, structural, medical, or mixed — used to avoid implying every lever is private willpower.' },
  { id: 'mental-workload', term: 'Mental workload',
    def: 'Multidimensional construct describing the cognitive demands of a task relative to operator capacity; measured subjectively, behaviorally, and/or physiologically in human factors.' },
  { id: 'nasa-tlx', term: 'NASA-TLX',
    def: 'Widely used multidimensional subjective workload scale (Hart & Staveland) with subscales such as mental demand, temporal demand, effort, and frustration.' },
  { id: 'process-factor', term: 'Process factor', lab: true,
    def: 'A scored exposure in CBI (e.g. interruption density, sleep disruption, recovery opportunity) as distinct from identity labels, which are not scored.' },
  { id: 'recovery-opportunity', term: 'Recovery opportunity',
    def: 'Time and conditions that allow physiological and psychological systems to down-regulate after demand; critical counterweight to allostatic accumulation.' },
  { id: 'toxic-load', term: 'Toxic load', lab: true,
    def: 'Highest CBI zone: unchecked demand likely eroding capacity; prioritize reducing load and restoring recovery and controllability.' },
  { id: 'trajectory', term: 'Trajectory', lab: true,
    def: 'Multi-day direction of CBI/latent load: accumulating, roughly stable, or recovering.' },
  { id: 'working-memory', term: 'Working memory',
    def: 'Limited-capacity system for holding and manipulating information in the short term; a bottleneck in cognitive ergonomics and CLT.' }
];
