/* Non-intrusive process questionnaire — maps to CBI factors. Not diagnostic. */
const QUESTIONS = [
  { id: 'q1', factor: 'ts', text: 'In a typical workday, I have to switch between very different tasks or systems.' },
  { id: 'q2', factor: 'wm', text: 'I often need to hold several pieces of information in mind at once to finish my work.' },
  { id: 'q3', factor: 'tp', text: 'I feel pressed for time relative to what is expected of me.' },
  { id: 'q4', factor: 'id', text: 'Interruptions (messages, walk-ups, alerts) break my focus many times a day.' },
  { id: 'q5', factor: 'el', text: 'My role requires managing other people’s emotions or tension, not only tasks.' },
  { id: 'q6', factor: 'ct', text: 'I have little real say over my pace, priorities, or how the work gets done.' },
  { id: 'q7', factor: 'sl', text: 'My sleep is shorter or more broken than I need for several nights a week.' },
  { id: 'q8', factor: 'ss', text: 'When work is hard, I do not have people I can honestly lean on.' },
  { id: 'q9', factor: 'ro', text: 'I get real off-time where work is not still running in my head.', invert: true },
  { id: 'q10', factor: 'al', text: 'Alcohol is part of how I wind down from stress more often than I would like.' },
  { id: 'q11', factor: 'su', text: 'I use other substances (including heavy caffeine or nicotine patterns) to push through load.' },
  { id: 'q12', factor: 'di', text: 'My eating pattern feels irregular or mostly on-the-run when stress is high.' },
  { id: 'q13', factor: 'mw', text: 'Physical fatigue or body strain makes ordinary demand feel heavier.' },
  { id: 'q14', factor: 'env', text: 'Noise, crowding, commute, or workspace conditions add strain beyond the work itself.' },
  { id: 'q15', factor: 'ms', text: 'I experience unfair treatment, stereotyping, or pressure tied to how others see my identity.' },
  { id: 'q16', factor: 'ed', text: 'Limited money, tools, or information access makes it harder to handle demands.' },
  { id: 'q17', factor: 'chr', text: 'An ongoing health issue uses a noticeable share of my daily energy.' },
  { id: 'q18', factor: 'med', text: 'Medication or treatment side effects (fog, sedation, sleep change) affect my days.' },
  { id: 'q19', factor: 'sen', text: 'Busy sensory environments (light, sound, crowds) tire me faster than they used to.' },
  { id: 'q20', factor: 'tbi', text: 'After a head injury or similar event, focus or fatigue still feels different than before.' },
  { id: 'q21', factor: 'tp', text: 'Deadlines stack so that finishing one thing only reveals three more behind it.' },
  { id: 'q22', factor: 'id', text: 'I rarely get a full hour of uninterrupted focus on one task.' },
  { id: 'q23', factor: 'el', text: 'Conflict, criticism, or emotional tension is a regular part of my week.' },
  { id: 'q24', factor: 'ct', text: 'When problems appear, I feel stuck without options that actually change anything.' },
  { id: 'q25', factor: 'sl', text: 'I wake up already tired more mornings than not.' },
  { id: 'q26', factor: 'ro', text: 'Even on days off, I check work or keep mentally rehearsing unfinished tasks.', invert: false },
  { id: 'q27', factor: 'ss', text: 'I can name at least one person who would help if I asked this week.', invert: true },
  { id: 'q28', factor: 'ts', text: 'Meetings, chats, and tasks constantly pull me between different mental modes.' },
  { id: 'q29', factor: 'wm', text: 'I lose track of steps or details because too much is active in my mind at once.' },
  { id: 'q30', factor: 'env', text: 'Getting to and from my responsibilities is itself exhausting or unpredictable.' },
  { id: 'q31', factor: 'geo', text: 'Weather, disaster risk, or instability in my area adds background worry.' },
  { id: 'q32', factor: 'ag', text: 'Recovery after hard days seems slower than it used to.' },
  { id: 'q33', factor: 'di', text: 'I skip meals or rely on ultra-convenient food when the week intensifies.' },
  { id: 'q34', factor: 'ms', text: 'I feel I have to work harder than others to be seen as equally capable.' },
  { id: 'q35', factor: 'ed', text: 'I lack training, credentials access, or tools that would make the same job easier.' },
  { id: 'q36', factor: 'el', text: 'I hide stress so others will not see me as less capable.' },
  { id: 'q37', factor: 'ro', text: 'I have a shutdown habit that usually works (walk, hobby, device boundary).', invert: true },
  { id: 'q38', factor: 'ct', text: 'Expectations of me change without clear conversation or agreement.' },
  { id: 'q39', factor: 'sl', text: 'Screens or work thoughts keep me from falling asleep when I intend to.' },
  { id: 'q40', factor: 'ss', text: 'Talking honestly about strain feels risky in my main environment.' },
  { id: 'q41', factor: 'wm', text: 'I need written external reminders more than before to keep work accurate.' },
  { id: 'q42', factor: 'tp', text: 'I say yes to new demands because saying no feels unsafe or disloyal.' },
  { id: 'q43', factor: 'chr', text: 'Pain, illness appointments, or symptoms regularly reshape my day.' },
  { id: 'q44', factor: 'sen', text: 'I need quiet or dimmer space to think clearly after busy settings.' },
  { id: 'q45', factor: 'al', text: 'I notice sleep or next-day mood is worse after evenings with alcohol.' },
  { id: 'q46', factor: 'id', text: 'People expect immediate replies outside core work hours.' },
  { id: 'q47', factor: 'ts', text: 'I end the day with many half-finished threads and open loops.' },
  { id: 'q48', factor: 'ro', text: 'I can take a real break without guilt when I need one.', invert: true },
  { id: 'q49', factor: 'ct', text: 'I know what “good enough” looks like for my main responsibilities.', invert: true },
  { id: 'q50', factor: 'ss', text: 'Someone would notice if I were struggling more than usual.', invert: true }
];
